### ISSUE TITLE
Speedtrap "crash"

### ISSUE THREAD

**Issue by Ericsson2003** [ExOptsTeam/NFSMWRaceFixes#3] opened 2020-12-09 12:01 UTC
Game quits unexpectedly, when you pass first fotoradar on Speedtrap events.

**Comment by trackmaniamatt** [comment] 2020-12-09 14:57
I have also tested this, and I too, am having the same problem. Not sure what's causing this.

**Comment by nlgzrgn** [comment] 2020-12-09 16:02
The issue is fixed with v1.0.0.1338 release. Thanks for reporting, have fun!

**Closed by nlgzrgn** 2020-12-09 16:02 UTC
